// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Note struct {
	ID         int64
	Title      string
	Content    string
	EntityID   int64
	EntityType string
}

type Resource struct {
	ID         int64
	Title      string
	Source     string
	SourceType string
	StatusID   int64
}

type ResourceTag struct {
	ResourceID int64
	TagID      int64
}

type Status struct {
	ID   int64
	Name string
}

type Tag struct {
	ID   int64
	Name string
}
