// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"strings"
)

const clearTags = `-- name: ClearTags :exec
DELETE FROM resource_tags
WHERE resource_id = ?
`

func (q *Queries) ClearTags(ctx context.Context, resourceID int64) error {
	_, err := q.db.ExecContext(ctx, clearTags, resourceID)
	return err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  title, content, entity_id, entity_type
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, title, content, entity_id, entity_type
`

type CreateNoteParams struct {
	Title      string
	Content    string
	EntityID   int64
	EntityType string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.Title,
		arg.Content,
		arg.EntityID,
		arg.EntityType,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.EntityID,
		&i.EntityType,
	)
	return i, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  title, source, source_type, status_id
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, title, source, source_type, status_id
`

type CreateResourceParams struct {
	Title      string
	Source     string
	SourceType string
	StatusID   int64
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.Title,
		arg.Source,
		arg.SourceType,
		arg.StatusID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id=?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE id=? LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.EntityID,
		&i.EntityType,
	)
	return i, err
}

const getNotes = `-- name: GetNotes :many
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE entity_id=? AND entity_type=?
`

type GetNotesParams struct {
	EntityID   int64
	EntityType string
}

func (q *Queries) GetNotes(ctx context.Context, arg GetNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotes, arg.EntityID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.EntityID,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResource = `-- name: GetResource :one
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM resources r
JOIN statuses s ON r.status_id = s.id
WHERE r.id = ? LIMIT 1
`

type GetResourceRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) GetResource(ctx context.Context, id int64) (GetResourceRow, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i GetResourceRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Title,
		&i.Resource.Source,
		&i.Resource.SourceType,
		&i.Resource.StatusID,
		&i.Status.ID,
		&i.Status.Name,
		&i.Status.Color,
	)
	return i, err
}

const getResourceTags = `-- name: GetResourceTags :many
SELECT t.id, t.name, t.color
FROM resource_tags rt
JOIN tags t ON rt.tag_id = t.id
WHERE rt.resource_id = ?
`

func (q *Queries) GetResourceTags(ctx context.Context, resourceID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getResourceTags, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResources = `-- name: GetResources :many
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM resources r
JOIN statuses s ON r.status_id = s.id
`

type GetResourcesRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) GetResources(ctx context.Context) ([]GetResourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, getResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesRow
	for rows.Next() {
		var i GetResourcesRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Title,
			&i.Resource.Source,
			&i.Resource.SourceType,
			&i.Resource.StatusID,
			&i.Status.ID,
			&i.Status.Name,
			&i.Status.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesNotes = `-- name: GetResourcesNotes :many
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE entity_id IN (/*SLICE:resources*/?) AND entity_type=?
`

type GetResourcesNotesParams struct {
	Resources  []int64
	EntityType string
}

func (q *Queries) GetResourcesNotes(ctx context.Context, arg GetResourcesNotesParams) ([]Note, error) {
	query := getResourcesNotes
	var queryParams []interface{}
	if len(arg.Resources) > 0 {
		for _, v := range arg.Resources {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resources*/?", strings.Repeat(",?", len(arg.Resources))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resources*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.EntityType)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.EntityID,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesTags = `-- name: GetResourcesTags :many
SELECT rt.resource_id, t.id, t.name, t.color
FROM resource_tags rt
JOIN tags t ON rt.tag_id = t.id
WHERE rt.resource_id IN (/*SLICE:resources*/?)
`

type GetResourcesTagsRow struct {
	ResourceID int64
	Tag        Tag
}

func (q *Queries) GetResourcesTags(ctx context.Context, resources []int64) ([]GetResourcesTagsRow, error) {
	query := getResourcesTags
	var queryParams []interface{}
	if len(resources) > 0 {
		for _, v := range resources {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resources*/?", strings.Repeat(",?", len(resources))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resources*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesTagsRow
	for rows.Next() {
		var i GetResourcesTagsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, color FROM statuses WHERE id=?
`

func (q *Queries) GetStatus(ctx context.Context, id int64) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, id)
	var i Status
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const getStatuses = `-- name: GetStatuses :many
SELECT id, name, color FROM statuses
`

func (q *Queries) GetStatuses(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTags = `-- name: GetTags :many
SELECT id, name, color FROM tags
`

func (q *Queries) GetTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatus = `-- name: SetStatus :exec
UPDATE resources
SET status_id = ?
WHERE id = ?
`

type SetStatusParams struct {
	StatusID int64
	ID       int64
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.ExecContext(ctx, setStatus, arg.StatusID, arg.ID)
	return err
}

const setTag = `-- name: SetTag :exec
INSERT INTO resource_tags (
  resource_id, tag_id
) VALUES (
  ?, ?
)
`

type SetTagParams struct {
	ResourceID int64
	TagID      int64
}

func (q *Queries) SetTag(ctx context.Context, arg SetTagParams) error {
	_, err := q.db.ExecContext(ctx, setTag, arg.ResourceID, arg.TagID)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET 
title=?,
content=?
WHERE id=?
RETURNING id, title, content, entity_id, entity_type
`

type UpdateNoteParams struct {
	Title   string
	Content string
	ID      int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Title, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.EntityID,
		&i.EntityType,
	)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources SET
title = ?,
source = ?,
source_type = ?,
status_id = ?
WHERE id = ?
RETURNING id, title, source, source_type, status_id
`

type UpdateResourceParams struct {
	Title      string
	Source     string
	SourceType string
	StatusID   int64
	ID         int64
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.Title,
		arg.Source,
		arg.SourceType,
		arg.StatusID,
		arg.ID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}
