// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const addResourceToCollection = `-- name: AddResourceToCollection :exec
INSERT INTO collection_resources (
  collection_id, resource_id
) VALUES (
  ?, ?
)
`

type AddResourceToCollectionParams struct {
	CollectionID int64
	ResourceID   int64
}

func (q *Queries) AddResourceToCollection(ctx context.Context, arg AddResourceToCollectionParams) error {
	_, err := q.db.ExecContext(ctx, addResourceToCollection, arg.CollectionID, arg.ResourceID)
	return err
}

const clearTags = `-- name: ClearTags :exec
DELETE FROM resource_tags
WHERE resource_id = ?
`

func (q *Queries) ClearTags(ctx context.Context, resourceID int64) error {
	_, err := q.db.ExecContext(ctx, clearTags, resourceID)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (
  title, description
) VALUES (
  ?, ?
)
RETURNING id, title, description
`

type CreateCollectionParams struct {
	Title       string
	Description sql.NullString
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, arg.Title, arg.Description)
	var i Collection
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  title, content, entity_id, entity_type
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, title, content, entity_id, entity_type
`

type CreateNoteParams struct {
	Title      string
	Content    string
	EntityID   int64
	EntityType string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.Title,
		arg.Content,
		arg.EntityID,
		arg.EntityType,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.EntityID,
		&i.EntityType,
	)
	return i, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  title, source, source_type, status_id
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, title, source, source_type, status_id
`

type CreateResourceParams struct {
	Title      string
	Source     string
	SourceType string
	StatusID   int64
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.Title,
		arg.Source,
		arg.SourceType,
		arg.StatusID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}

const createStatus = `-- name: CreateStatus :one
INSERT INTO statuses (
 name, color
) VALUES (
  ?, ?
)
RETURNING id, name, color
`

type CreateStatusParams struct {
	Name  string
	Color string
}

func (q *Queries) CreateStatus(ctx context.Context, arg CreateStatusParams) (Status, error) {
	row := q.db.QueryRowContext(ctx, createStatus, arg.Name, arg.Color)
	var i Status
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (
 name, color
) VALUES (
  ?, ?
)
RETURNING id, name, color
`

type CreateTagParams struct {
	Name  string
	Color string
}

func (q *Queries) CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, arg.Name, arg.Color)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id=?
`

func (q *Queries) DeleteCollection(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes WHERE id=?
`

func (q *Queries) DeleteNote(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const deleteStatus = `-- name: DeleteStatus :exec
DELETE FROM statuses WHERE id=?
`

func (q *Queries) DeleteStatus(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStatus, id)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id=?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const filterCollectionResources = `-- name: FilterCollectionResources :many
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM resources r
JOIN collection_resources cr ON r.id = cr.resource_id
jOIN statuses s ON r.status_id = s.id
LEFT jOIN resource_tags rt ON r.id = rt.resource_id
WHERE (? IS NULL OR s.id IN (/*SLICE:statuses*/?)) AND (? IS NULL OR rt.tag_id IN (/*SLICE:tags*/?)) AND cr.collection_id = ?
GROUP BY r.id
HAVING ? IS NULL OR COUNT(DISTINCT rt.tag_id) = ?
`

type FilterCollectionResourcesParams struct {
	Column1      interface{}
	Statuses     []int64
	Column3      interface{}
	Tags         []int64
	CollectionID int64
	FilterTags   interface{}
	TagsCount    int64
}

type FilterCollectionResourcesRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) FilterCollectionResources(ctx context.Context, arg FilterCollectionResourcesParams) ([]FilterCollectionResourcesRow, error) {
	query := filterCollectionResources
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Column1)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column3)
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.CollectionID)
	queryParams = append(queryParams, arg.FilterTags)
	queryParams = append(queryParams, arg.TagsCount)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterCollectionResourcesRow
	for rows.Next() {
		var i FilterCollectionResourcesRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Title,
			&i.Resource.Source,
			&i.Resource.SourceType,
			&i.Resource.StatusID,
			&i.Status.ID,
			&i.Status.Name,
			&i.Status.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filterReousrces = `-- name: FilterReousrces :many
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM resources r
jOIN statuses s ON r.status_id = s.id
LEFT jOIN resource_tags rt ON r.id = rt.resource_id
WHERE (? IS NULL OR s.id IN (/*SLICE:statuses*/?)) AND (? IS NULL OR rt.tag_id IN (/*SLICE:tags*/?))
GROUP BY r.id
HAVING ? IS NULL OR COUNT(DISTINCT rt.tag_id) = ?
`

type FilterReousrcesParams struct {
	Column1    interface{}
	Statuses   []int64
	Column3    interface{}
	Tags       []int64
	FilterTags interface{}
	TagsCount  int64
}

type FilterReousrcesRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) FilterReousrces(ctx context.Context, arg FilterReousrcesParams) ([]FilterReousrcesRow, error) {
	query := filterReousrces
	var queryParams []interface{}
	queryParams = append(queryParams, arg.Column1)
	if len(arg.Statuses) > 0 {
		for _, v := range arg.Statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(arg.Statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.Column3)
	if len(arg.Tags) > 0 {
		for _, v := range arg.Tags {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:tags*/?", strings.Repeat(",?", len(arg.Tags))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:tags*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.FilterTags)
	queryParams = append(queryParams, arg.TagsCount)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterReousrcesRow
	for rows.Next() {
		var i FilterReousrcesRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Title,
			&i.Resource.Source,
			&i.Resource.SourceType,
			&i.Resource.StatusID,
			&i.Status.ID,
			&i.Status.Name,
			&i.Status.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollection = `-- name: GetCollection :one
SELECT id, title, description FROM collections
WHERE id=?
`

func (q *Queries) GetCollection(ctx context.Context, id int64) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const getCollectionNotes = `-- name: GetCollectionNotes :many
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE entity_type='collection' AND entity_id=?
`

func (q *Queries) GetCollectionNotes(ctx context.Context, entityID int64) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionNotes, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.EntityID,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionResources = `-- name: GetCollectionResources :many
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM collection_resources cr
JOIN resources r ON cr.resource_id = r.id
JOIN statuses s ON r.status_id = s.id
WHERE cr.collection_id=?
`

type GetCollectionResourcesRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) GetCollectionResources(ctx context.Context, collectionID int64) ([]GetCollectionResourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCollectionResources, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionResourcesRow
	for rows.Next() {
		var i GetCollectionResourcesRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Title,
			&i.Resource.Source,
			&i.Resource.SourceType,
			&i.Resource.StatusID,
			&i.Status.ID,
			&i.Status.Name,
			&i.Status.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollections = `-- name: GetCollections :many
SELECT id, title, description FROM collections
`

func (q *Queries) GetCollections(ctx context.Context) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, getCollections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(&i.ID, &i.Title, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionsResources = `-- name: GetCollectionsResources :many
SELECT cr.collection_id, r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM collection_resources cr
JOIN resources r ON cr.resource_id = r.id
JOIN statuses s ON r.status_id = s.id
WHERE cr.collection_id IN (/*SLICE:collections*/?)
`

type GetCollectionsResourcesRow struct {
	CollectionID int64
	Resource     Resource
	Status       Status
}

func (q *Queries) GetCollectionsResources(ctx context.Context, collections []int64) ([]GetCollectionsResourcesRow, error) {
	query := getCollectionsResources
	var queryParams []interface{}
	if len(collections) > 0 {
		for _, v := range collections {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:collections*/?", strings.Repeat(",?", len(collections))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:collections*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCollectionsResourcesRow
	for rows.Next() {
		var i GetCollectionsResourcesRow
		if err := rows.Scan(
			&i.CollectionID,
			&i.Resource.ID,
			&i.Resource.Title,
			&i.Resource.Source,
			&i.Resource.SourceType,
			&i.Resource.StatusID,
			&i.Status.ID,
			&i.Status.Name,
			&i.Status.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNote = `-- name: GetNote :one
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE id=? LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, id int64) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.EntityID,
		&i.EntityType,
	)
	return i, err
}

const getNotes = `-- name: GetNotes :many
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE entity_id=? AND entity_type=?
`

type GetNotesParams struct {
	EntityID   int64
	EntityType string
}

func (q *Queries) GetNotes(ctx context.Context, arg GetNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, getNotes, arg.EntityID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.EntityID,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResource = `-- name: GetResource :one
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM resources r
JOIN statuses s ON r.status_id = s.id
WHERE r.id = ? LIMIT 1
`

type GetResourceRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) GetResource(ctx context.Context, id int64) (GetResourceRow, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i GetResourceRow
	err := row.Scan(
		&i.Resource.ID,
		&i.Resource.Title,
		&i.Resource.Source,
		&i.Resource.SourceType,
		&i.Resource.StatusID,
		&i.Status.ID,
		&i.Status.Name,
		&i.Status.Color,
	)
	return i, err
}

const getResourceTags = `-- name: GetResourceTags :many
SELECT t.id, t.name, t.color
FROM resource_tags rt
JOIN tags t ON rt.tag_id = t.id
WHERE rt.resource_id = ?
`

func (q *Queries) GetResourceTags(ctx context.Context, resourceID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getResourceTags, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResources = `-- name: GetResources :many
SELECT r.id, r.title, r.source, r.source_type, r.status_id, s.id, s.name, s.color FROM resources r
JOIN statuses s ON r.status_id = s.id
`

type GetResourcesRow struct {
	Resource Resource
	Status   Status
}

func (q *Queries) GetResources(ctx context.Context) ([]GetResourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, getResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesRow
	for rows.Next() {
		var i GetResourcesRow
		if err := rows.Scan(
			&i.Resource.ID,
			&i.Resource.Title,
			&i.Resource.Source,
			&i.Resource.SourceType,
			&i.Resource.StatusID,
			&i.Status.ID,
			&i.Status.Name,
			&i.Status.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesNotes = `-- name: GetResourcesNotes :many
SELECT id, title, content, entity_id, entity_type FROM notes
WHERE entity_id IN (/*SLICE:resources*/?) AND entity_type=?
`

type GetResourcesNotesParams struct {
	Resources  []int64
	EntityType string
}

func (q *Queries) GetResourcesNotes(ctx context.Context, arg GetResourcesNotesParams) ([]Note, error) {
	query := getResourcesNotes
	var queryParams []interface{}
	if len(arg.Resources) > 0 {
		for _, v := range arg.Resources {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resources*/?", strings.Repeat(",?", len(arg.Resources))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resources*/?", "NULL", 1)
	}
	queryParams = append(queryParams, arg.EntityType)
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.EntityID,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getResourcesTags = `-- name: GetResourcesTags :many
SELECT rt.resource_id, t.id, t.name, t.color
FROM resource_tags rt
JOIN tags t ON rt.tag_id = t.id
WHERE rt.resource_id IN (/*SLICE:resources*/?)
`

type GetResourcesTagsRow struct {
	ResourceID int64
	Tag        Tag
}

func (q *Queries) GetResourcesTags(ctx context.Context, resources []int64) ([]GetResourcesTagsRow, error) {
	query := getResourcesTags
	var queryParams []interface{}
	if len(resources) > 0 {
		for _, v := range resources {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:resources*/?", strings.Repeat(",?", len(resources))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:resources*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetResourcesTagsRow
	for rows.Next() {
		var i GetResourcesTagsRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.Tag.ID,
			&i.Tag.Name,
			&i.Tag.Color,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStatus = `-- name: GetStatus :one
SELECT id, name, color FROM statuses WHERE id=?
`

func (q *Queries) GetStatus(ctx context.Context, id int64) (Status, error) {
	row := q.db.QueryRowContext(ctx, getStatus, id)
	var i Status
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const getStatuses = `-- name: GetStatuses :many
SELECT id, name, color FROM statuses
`

func (q *Queries) GetStatuses(ctx context.Context) ([]Status, error) {
	rows, err := q.db.QueryContext(ctx, getStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTag = `-- name: GetTag :one
SELECT id, name, color FROM tags
WHERE id=?
`

func (q *Queries) GetTag(ctx context.Context, id int64) (Tag, error) {
	row := q.db.QueryRowContext(ctx, getTag, id)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const getTags = `-- name: GetTags :many
SELECT id, name, color FROM tags
`

func (q *Queries) GetTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, getTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tag
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeResourceFromCollection = `-- name: RemoveResourceFromCollection :exec
DELETE FROM collection_resources WHERE resource_id=? AND collection_id=?
`

type RemoveResourceFromCollectionParams struct {
	ResourceID   int64
	CollectionID int64
}

func (q *Queries) RemoveResourceFromCollection(ctx context.Context, arg RemoveResourceFromCollectionParams) error {
	_, err := q.db.ExecContext(ctx, removeResourceFromCollection, arg.ResourceID, arg.CollectionID)
	return err
}

const setStatus = `-- name: SetStatus :exec
UPDATE resources
SET status_id = ?
WHERE id = ?
`

type SetStatusParams struct {
	StatusID int64
	ID       int64
}

func (q *Queries) SetStatus(ctx context.Context, arg SetStatusParams) error {
	_, err := q.db.ExecContext(ctx, setStatus, arg.StatusID, arg.ID)
	return err
}

const setTag = `-- name: SetTag :exec
INSERT INTO resource_tags (
  resource_id, tag_id
) VALUES (
  ?, ?
)
`

type SetTagParams struct {
	ResourceID int64
	TagID      int64
}

func (q *Queries) SetTag(ctx context.Context, arg SetTagParams) error {
	_, err := q.db.ExecContext(ctx, setTag, arg.ResourceID, arg.TagID)
	return err
}

const updateCollection = `-- name: UpdateCollection :one
UPDATE collections SET
title=?,
description=?
WHERE id=?
RETURNING id, title, description
`

type UpdateCollectionParams struct {
	Title       string
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateCollection(ctx context.Context, arg UpdateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, updateCollection, arg.Title, arg.Description, arg.ID)
	var i Collection
	err := row.Scan(&i.ID, &i.Title, &i.Description)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET 
title=?,
content=?
WHERE id=?
RETURNING id, title, content, entity_id, entity_type
`

type UpdateNoteParams struct {
	Title   string
	Content string
	ID      int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote, arg.Title, arg.Content, arg.ID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.EntityID,
		&i.EntityType,
	)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources SET
title = ?,
source = ?,
source_type = ?,
status_id = ?
WHERE id = ?
RETURNING id, title, source, source_type, status_id
`

type UpdateResourceParams struct {
	Title      string
	Source     string
	SourceType string
	StatusID   int64
	ID         int64
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.Title,
		arg.Source,
		arg.SourceType,
		arg.StatusID,
		arg.ID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}

const updateStatus = `-- name: UpdateStatus :one
UPDATE statuses SET
name=?,
color=?
WHERE id=?
RETURNING id, name, color
`

type UpdateStatusParams struct {
	Name  string
	Color string
	ID    int64
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (Status, error) {
	row := q.db.QueryRowContext(ctx, updateStatus, arg.Name, arg.Color, arg.ID)
	var i Status
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}

const updateTag = `-- name: UpdateTag :one
UPDATE tags SET
name=?,
color=?
WHERE id=?
RETURNING id, name, color
`

type UpdateTagParams struct {
	Name  string
	Color string
	ID    int64
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) (Tag, error) {
	row := q.db.QueryRowContext(ctx, updateTag, arg.Name, arg.Color, arg.ID)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.Color)
	return i, err
}
