// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resources (
  title, source, source_type, status_id
) VALUES (
  ?, ?, ?, ?
)
RETURNING id, title, source, source_type, status_id
`

type CreateResourceParams struct {
	Title      string
	Source     string
	SourceType string
	StatusID   int64
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, createResource,
		arg.Title,
		arg.Source,
		arg.SourceType,
		arg.StatusID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources
WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const getResource = `-- name: GetResource :one
SELECT id, title, source, source_type, status_id FROM resources
WHERE id = ? LIMIT 1
`

func (q *Queries) GetResource(ctx context.Context, id int64) (Resource, error) {
	row := q.db.QueryRowContext(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}

const getResources = `-- name: GetResources :many
SELECT id, title, source, source_type, status_id FROM resources
`

func (q *Queries) GetResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.QueryContext(ctx, getResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Resource
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.SourceType,
			&i.StatusID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources SET
title = ?,
source = ?,
source_type = ?,
status_id = ?
WHERE id = ?
RETURNING id, title, source, source_type, status_id
`

type UpdateResourceParams struct {
	Title      string
	Source     string
	SourceType string
	StatusID   int64
	ID         int64
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRowContext(ctx, updateResource,
		arg.Title,
		arg.Source,
		arg.SourceType,
		arg.StatusID,
		arg.ID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Source,
		&i.SourceType,
		&i.StatusID,
	)
	return i, err
}
