CREATE TABLE IF NOT EXISTS resources (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  source TEXT NOT NULL,
  source_type TEXT NOT NULL,
  status_id INTEGER NOT NULL,
  FOREIGN KEY(status_id) REFERENCES statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS statuses (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS resource_tags (
  resource_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  FOREIGN KEY(resource_id) REFERENCES resources(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY(tag_id) REFERENCES tags(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS notes (
  id INTEGER PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  entity_id INTEGER NOT NULL,
  entity_type TEXT NOT NULL
);
